/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myHangman;


/**
 *
 * @author Arsh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setBounds(300,300,600,434);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        highscoreButton = new javax.swing.JButton();
        creditButton = new javax.swing.JButton();
        symbol = new javax.swing.JLabel();
        whiteEyeBackGround = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();
        blackBackgGround = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        playButton.setBackground(new java.awt.Color(51, 102, 255));
        playButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        playButton.setText("PLAY");
        playButton.setBorder(null);
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButtonMouseEntered(evt);
            }
        });
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(410, 220, 170, 50);

        highscoreButton.setBackground(new java.awt.Color(51, 102, 255));
        highscoreButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        highscoreButton.setText("HIGHSCORES");
        highscoreButton.setBorder(null);
        highscoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(highscoreButton);
        highscoreButton.setBounds(410, 280, 170, 50);

        creditButton.setBackground(new java.awt.Color(51, 102, 255));
        creditButton.setFont(new java.awt.Font("Bauhaus 93", 2, 24)); // NOI18N
        creditButton.setText("CREDITS");
        creditButton.setBorder(null);
        creditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creditButton);
        creditButton.setBounds(410, 340, 170, 50);
        getContentPane().add(symbol);
        symbol.setBounds(30, 30, 180, 188);
        getContentPane().add(whiteEyeBackGround);
        whiteEyeBackGround.setBounds(90, 110, 60, 25);
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 600, 400);

        blackBackgGround.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(blackBackgGround);
        blackBackgGround.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        new Play().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_playButtonActionPerformed

    private void highscoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreButtonActionPerformed
        // TODO add your handling code here:
        new Highscores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_highscoreButtonActionPerformed

    private void creditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditButtonActionPerformed
        // TODO add your handling code here:
        new Credits().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creditButtonActionPerformed

    private void playButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_playButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JPanel blackBackgGround;
    private javax.swing.JButton creditButton;
    private javax.swing.JButton highscoreButton;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel symbol;
    private javax.swing.JLabel whiteEyeBackGround;
    // End of variables declaration//GEN-END:variables
}
